/*
Isaac Powrie
2018-12-08
numTblMagic.c
*/

/*
Contains the struct definition for tables, as well
as the headers and descriptions of files
*/

struct TablesMeta {
	int numTbls;
	int numColumns;
	int numPlaces;
};

/*
Function Headers
*/

// fillTblMeta(): fills the structure with the
// table metadata; number of columns, places per
// table, and number of tables
void fillTblMeta(struct TablesMeta* tbls);

// playGame(): parent function which directs the 
// two main portions of the game, getting the user
// choice tables, and determining the answer
void playGame(struct TablesMeta* tbls);

// displayTable(): prints up a table of numbers based
// on the table number input as well as the table 
// metadata
void displayTable(int tblNum, struct TablesMeta* tbls);

// userChoice(): allows the user to shift through the 
// tables generated by ther number of tables selection
// and choose the tables which contain the user's answer
void userChoice(int* userChoices, struct TablesMeta* tbls);

// determineAnswer(): take the array of table numbers 
// and determine the user's answer
void determineAnswer(int* userChoices);
